# Generated by Django 3.2.13 on 2022-09-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('card_no', models.IntegerField()),
                ('expiry_month', models.DateField()),
                ('expiry_year', models.DateField()),
                ('cvv_no', models.IntegerField()),
                ('first_name', models.CharField(max_length=23)),
                ('last_name', models.CharField(max_length=43)),
                ('Address1', models.TextField()),
                ('Address2', models.TextField()),
                ('city', models.CharField(max_length=29)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('no_of_seats', models.IntegerField()),
                ('account', models.CharField(max_length=30)),
                ('filter', models.CharField(max_length=30)),
                ('hours', models.IntegerField()),
                ('minute', models.IntegerField()),
            ],
        ),
    ]
